FIRST_NAMES = [
    "Anna",
    "Daan",
    "Emma",
    "Sem",
    "Julia",
    "Lucas",
    "Sophie",
    "Finn",
    "Lotte",
    "Milan",
    "Sara",
    "Noah",
    "Eva",
    "Levi",
    "Fleur",
    "Thomas",
    "Isa",
    "Ruben",
    "Lisa",
    "Jesse",
    "Priya",
    "Arjun",
    "Mei",
    "Omar",
    "Elena",
    "Mateo",
    "Chloe",
    "Lukas",
    "Amira",
    "Jan",
]

LAST_NAMES = [
    "de Jong",
    "Jansen",
    "de Vries",
    "van den Berg",
    "van Dijk",
    "Bakker",
    "Visser",
    "Smit",
    "Meijer",
    "de Boer",
    "Mulder",
    "de Groot",
    "Bos",
    "Vos",
    "Peters",
    "Hendriks",
    "Dekker",
    "Brouwer",
    "Kumar",
    "Chen",
    "Haddad",
    "Garcia",
    "Muller",
    "Dubois",
    "Rossi",
    "Novak",
]

MERCHANT_WORDS = [
    "Albert",
    "Noord",
    "Central",
    "Tulip",
    "Harbor",
    "Canal",
    "Orange",
    "Linden",
    "Delta",
    "Polder",
    "Windmill",
    "Metro",
    "Urban",
    "Sunny",
    "Blue",
    "Green",
    "Royal",
    "Market",
]

MERCHANT_SUFFIX = ["Store", "Shop", "Market", "Cafe", "Express", "BV", "Company", "Outlet", "Plaza"]

# mcc, amount multiplier vs a typical card payment, popularity weight
MCC_PROFILE = {
    "5411": (1.4, 30),
    "5812": (1.8, 12),
    "5814": (0.6, 14),
    "5541": (2.4, 8),
    "4111": (0.5, 10),
    "4121": (1.1, 4),
    "5311": (2.0, 4),
    "5651": (2.8, 4),
    "5732": (6.0, 2),
    "5912": (0.9, 5),
    "4814": (1.6, 2),
    "4900": (3.5, 2),
    "5942": (1.0, 2),
    "7832": (0.9, 3),
    "4511": (12.0, 1),
    "7011": (9.0, 1),
    "5200": (3.0, 2),
    "5999": (1.2, 6),
}

CURRENCIES = {"USD": 0.92, "GBP": 1.17}
